#!/bin/bash -e
#
# Source code post-build script complementary to the application server post-build script provided by STARTX.
# This script will be executed after the building process (s2i)
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

echoNotVerbose "Sample postgres application pre-build hook"
echoVerbose ""
echoVerbose "+====================================================="
echoVerbose "Sample postgres application pre-build hook"
echoVerbose "+====================================================="

# if you want to fail the post-build hook, exit with error code > 0
# exit 1;