#!/bin/bash -e
#
# Source code post-deploy script complementary to the application server post-deploy script provided by STARTX.
# This script will be executed after the deployement of a new container (or pod)
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

echoNotVerbose "Sample postgres application post-deploy hook"
echoVerbose ""
echoVerbose "+====================================================="
echoVerbose "Sample postgres application post-deploy hook"
echoVerbose "+====================================================="

# if you want to fail the post-deploy hook, exit with error code > 0
# exit 1;